# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sRNKDotg904bkUloNh6awPsFKu63m4B+SUSFXbqbQqHDf6iqGzcSKavhG+4La3nVHYbkQxmvIOykJJCGOheUlX2a7rtL54tOkNCiwURFwlqwiBYg75zRNow/L1bvT0qTxlPxZUELOJCZEFpoxB7R0L1RrDD5bFsye5IxtmxpXH2YEzXIfYpxfBnI5TZeusHwSm16RbX8TpCbMPple7WL/+A83duM7+Mu0UKm42YiIqvXAXKJaZvq5qEcaCPRDHn06JyibM8afWMWnZO/XTSBCKZ28WugAx7+gQP/T1d5YieKNsPhQKaT8ZuLJ5gxRakg4UhnWZjLi70EhVQjsplZWDl7wf1/rvhzgSafhpqFMJswDD2vdKDU9C2P4fADxefSqnGKOWRuCYdhH3inuEzQpRFAOKIMV8668t+9+tgsakfxRjJ03TBROEHYv8sH/zdficzKnIcJ48AQKlMkQpuQWuSzqhMp8oCstchFG4yDJhoQyK8jeqhPVu5uj9CD7prezeX1hroMo2VJvjbdS//RPrZ057dd4OEOhKmTux9MRIPt8p4le/FmYiRYUwVPBISLosXMfKZjhvnNzqkmuOCxhs75TCXMaJB36aK0kw09LeM2t32/Uc0WTmAohqj4uIfys6b4ZpEMNh5eHRM1wXnUxg06GAbqVxFccTtFtGmdygs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
