travis:
  secure:
    BINSTAR_TOKEN: s1H5gADwTUqp33pv+kxr5xJa4FOcEsXQHcAVbuSgQvVtBoEXcU8oGMRyfgPYTEOlfRxi1ysrlWlSC6yA0yTLlTYCFOe81UEZcYPOfIIZ0yLRRETps+1PD2HOJchlwySyVBje6pHpvzbIfrv/MjLo7GJaCztPDxcxzadN07FeKpIDs5/JoXf845LVZjaesgTC5FCCgrCfLBPZRGBvZQLjalQu2aricVWDzuViJlI2/JyWTWIGQvSsTO7KbSzoiTyvdSLBMzRnGb5JwJbGqr8JvRdscAh/OFN6Nwc3vq+ar2NmxlUzfMkbuG9bEIWveu1en6j/nSMWopU+yPuv0oc25fuplS2bWX/pQdG4XyFHMLngAZ7QC7HiJunq9bNAlkbaCiuEYk6vNoaGQVjiSJVfy4OMJ8rL1Ovvtbn3HAuVACgZHC79aLZl9AGN+Mjl0dpJ901Gey9fqZH8++Qln+rvwp0c6am8UXpDexbHyFTc2xn6/EjHkgQUhdMUVGPbUO4/TxO4qfoZL62xZDj8LAdoJHw6P1j3irYloZq9xn+TRBJTp5ZvQhCln62NbWokpP+2NIwjFNrpSUMGGuNrwbHoiUcpRvf42tYamjFZnsZzCkeWHZ6SvFEg/Y1Ut30VZqSdX/rU+QWy8K+VqlWjsyCkTN76r1IRomewYrH7vpeEkfg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
