travis:
  secure:
    BINSTAR_TOKEN: sRNKDotg904bkUloNh6awPsFKu63m4B+SUSFXbqbQqHDf6iqGzcSKavhG+4La3nVHYbkQxmvIOykJJCGOheUlX2a7rtL54tOkNCiwURFwlqwiBYg75zRNow/L1bvT0qTxlPxZUELOJCZEFpoxB7R0L1RrDD5bFsye5IxtmxpXH2YEzXIfYpxfBnI5TZeusHwSm16RbX8TpCbMPple7WL/+A83duM7+Mu0UKm42YiIqvXAXKJaZvq5qEcaCPRDHn06JyibM8afWMWnZO/XTSBCKZ28WugAx7+gQP/T1d5YieKNsPhQKaT8ZuLJ5gxRakg4UhnWZjLi70EhVQjsplZWDl7wf1/rvhzgSafhpqFMJswDD2vdKDU9C2P4fADxefSqnGKOWRuCYdhH3inuEzQpRFAOKIMV8668t+9+tgsakfxRjJ03TBROEHYv8sH/zdficzKnIcJ48AQKlMkQpuQWuSzqhMp8oCstchFG4yDJhoQyK8jeqhPVu5uj9CD7prezeX1hroMo2VJvjbdS//RPrZ057dd4OEOhKmTux9MRIPt8p4le/FmYiRYUwVPBISLosXMfKZjhvnNzqkmuOCxhs75TCXMaJB36aK0kw09LeM2t32/Uc0WTmAohqj4uIfys6b4ZpEMNh5eHRM1wXnUxg06GAbqVxFccTtFtGmdygs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
