travis:
  secure:
    BINSTAR_TOKEN: PsFLtZwrpRWcly3okEmKIK+YtfNV4MN0a4+2VMn9B0K0Id74WAAWcbwp9gNyn6bAQV0WLdWrJHU1oVfy39VoM1acr7NcGkRmtAnNUmiirADFWGfKOLETXmcVp1I36vgthXNG4QxKE7bo2JWHRJY0d1GpVsj6+ZTw2teCbO1CE1Og3L9ZUPE2b6V1Wp/8ye0UT+JDk3HxKFQ0YxdhgUVBNMN9fUMUQkcOzeaDzC4WuBNmrxZ6YIP9J9j+tPVUQd1ESG98/X4bdlmVuqH/RGwaav1HJuiHyg6FO7DAcAWBmHRsvJj0bAcG2ffGVaiXMfQZbAR9nPiNJ5GwxtFslFCHsm9kBETUV6EYvIMqRrHkvVam8QTmX/hNwgRcqLVS9IJ+VNnfcA5FMVnPXlPuLsJDu8OcYs+l7C37RuSoKjWMCEvLmMR4a+xhPgY7PfrIO69NWgc3CWie+n5mj9GG0w4X6hwg8Uc38CuR9f2GHUHJMDvaCVJS3OQQfOxHgtZyXULhpgCDBJl3CEp/KLePV75Y9etYiYl0c9yn3TN2Qz5OjXNRS/kAlgknC+ljDbx3a/Pg9yH7moafNpkVDyBtnSeQ3ZNE/7dMMAMmzeQzrUIJ1AD0KOypkQCbUEhbsHGrA4Q1rqoc7B7vKZue6kNOuVm0BA69FwD+eXZlNtSnGhD4avg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
