travis:
  secure:
    BINSTAR_TOKEN: cAG2uh/kdOzww9ISfm+NxzgMICC5uPgtbWXLl+fkWATK6Hd1yNC3T1mprzthepzrrSygMVxXF0UVtt9T2MHlJt6w9HyJjHQ/1w2KdFZTPUgbK1PTf2A/cOCOREiiQHp2FiMItKLmfCcw6pfMil66290NeGezDnylVti/TMhF2s4f+ZRjcU3cy3gJtHOmYG0FZ7oRGxPaUBSycnjiGLcGnkUL3H07cLInhjaP4xlDHS/DZ0Oteq9Szmh7kuriUULTjWbP/z/ygiuURJxRch7r4CZa3yVw8+yfqO08oTexg0iyz7IMmEkdRfKTC2ZwrW7EUOgjdprnJfsHtkIMtKTn8tP6RYmVv/Zu/2krevU7k/7JTel1keNQbmW/UDjEg1Mqe//IU32VJGhRc/gF+OLc3XAI1PXYyJC8dG7T2G0gaaDQbZmTUUPQdurnqjxxtZk37nuT6jMHatUTONe2qpTWusCO8tL9+KwivM8qJBzI7RXwhzgiitay1Mk1STuaffioQrGewID4eL2HerC7oKAAWAb8cru50eaEgfnERTXf9944EelFEu2ku7+ZuKfuJLbfMBl8IydpWI3OTDgBgzlerhQkpZ46VWx5BPm+93D2/uYOVJMuErhOKt/3o9PryEiGntay4UGU2Xuz08CWNZ9jNjEnSHtfpliHsiP4prDqMfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
